#ifndef ERRS_H__
#define ERRS_H__

#define ERR_OK 0
#define ERR_FIRST_FORMAT 1
#define ERR_SECOND_FORMAT 2
#define ERR_FIRST_MANTISS_SIZE 3
#define ERR_SECOND_MANTISS_SIZE 4
#define ERR_FIRST_ORDER_SIZE 5
#define ERR_SECOND_ORDER_SIZE 6
#define ERR_NO_ARGS 7
#define ERR_RESULT_RANGE 8

#define ERR_FORMAT 101
#define ERR_MANTISS_SIZE 102
#define ERR_ORDER_SIZE 103
#define ERR_MANTISS_EMPTY 104
#define ERR_IO 105
#define ERR_STR_RANGE 106
#define ERR_STR_EMPTY 107

#endif
