#include <stdio.h>

#define MAX_FIRST_MANTISS_SIZE 35
#define MAX_SECOND_MANTISS_SIZE 40
#define MAX_RESULT_MANTISS_SIZE 40

#define MAX_FIRST_ORDER_SIZE 5
#define MAX_SECOND_ORDER_SIZE 5
#define MAX_RESULT_ORDER_SIZE 5